# cicd workflow for dev branch
name: Live CI/CD Pipeline

on:
  push:
    branches:
      - live

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Environment File
        run: |
          echo "${{ secrets.LIVE_ENV_FILE }}" > ./setting/default.env
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build . -t gunwoo99/during_ai_live:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push gunwoo99/during_ai_live:latest
